import { useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowUpRight, Award, Check, Code2, Download, ExternalLink, Mail, Menu, MessageCircle, Send, Sparkles, X } from 'lucide-react';

const Github = ({ size = 18 }: { size?: number }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.4 5.4 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"/><path d="M9 18c-4.51 2-5-2-7-2"/></svg>;
const Linkedin = ({ size = 18 }: { size?: number }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect width="4" height="12" x="2" y="9"/><circle cx="4" cy="4" r="2"/></svg>;

const projects = [
  { title: 'PixelBros Web Agency + Intranet', description: 'Sitio corporativo y sistema intranet para la agencia digital PixelBros, centralizando la gestión de clientes y proyectos.', tech: ['React', 'Node.js', 'Express', 'PostgreSQL', 'TailwindCSS'], image: '/assets/images/pixelbros.png', demo: 'https://www.pixelbros.pe/', github: 'https://github.com/hxtxrchq/PixelBros', type: 'web' },
  { title: 'Detección de patrones anómalos', description: 'Modelo híbrido de IA con Autoencoder y Random Forest para detectar patrones anómalos en transacciones, con visor en tiempo real.', tech: ['Python', 'Angular', 'WebSockets', 'Docker'], image: '/assets/images/deteccion_de_fraudes.png', demo: 'https://frontend-ae-rf.vercel.app/auth/login', type: 'ia' },
  { title: 'MiniMarketGG', description: 'Sistema de ventas y control de inventario de escritorio para un minimarket, con inicio de sesión y configuración de productos.', tech: ['Java', 'MySQL'], image: '/assets/images/MiniMarketGG.png', github: 'https://github.com/hxtxrchq/MiniMarketGG', type: 'desktop' },
  { title: 'ContentLab', description: 'Aplicación web para controlar el flujo de trabajo de una agencia de marketing, aprobaciones y contenido automatizado con IA.', tech: ['React', 'Node.js', 'Express', 'TailwindCSS'], image: '/assets/images/contentlab.png', github: 'https://github.com/hxtxrchq/Content_Lab', type: 'web' },
  { title: 'Versyo Store - E-commerce', description: 'Plataforma para comprar productos, hacer seguimiento de pedidos y administrar el catálogo desde un panel interno.', tech: ['React', 'TypeScript', 'PostgreSQL'], image: '/assets/images/Versyo logo .png', demo: 'https://versyo.chiqo.site/', github: 'https://github.com/hxtxrchq/backend-versyo', type: 'web' },
  { title: 'Visor 3D web', description: 'Visor en línea para presentar modelos arquitectónicos .glb/.gltf directamente en el navegador y desde cualquier dispositivo.', tech: ['React', 'JavaScript', 'WebGL'], image: '/assets/images/visor-kath3d.png', demo: 'https://kath-3d.chiqo.site/', github: 'https://github.com/hxtxrchq/3d-render-kath', type: 'web' },
  { title: 'Modelo de enfermedades en frutas', description: 'Sistema con modelos de aprendizaje profundo para identificar enfermedades en frutas y mejorar el control de calidad agroindustrial.', tech: ['Python', 'TensorFlow', 'CNN'], image: '/assets/images/Detección_De_Frutas - IA.png', demo: 'https://fruitdetective.vercel.app/', github: 'https://github.com/hxtxrchq/backend-fast-api-DeteccionFrutas', type: 'ia' },
  { title: 'TrendSpace', description: 'Plataforma de comercio electrónico colaborativo donde los usuarios votan, proponen y apoyan diseños de moda.', tech: ['HTML', 'CSS', 'JavaScript', 'MySQL'], image: '/assets/images/trendSpace-Web.png', demo: 'https://trendspace.hubstem.org/', github: 'https://github.com/hxtxrchq/TrendSpacev1', type: 'web' },
  { title: 'ECEL Ingeniería & Construcción', description: 'Sitio corporativo con servicios, proyectos y respaldo técnico para una empresa de ingeniería y construcción.', tech: ['React', 'TypeScript', 'TailwindCSS'], image: '/assets/images/ecel-peru.png', demo: 'https://www.ecelperu.org/', github: 'https://github.com/hxtxrchq/ECEL', type: 'web' },
  { title: 'PayReminder App', description: 'Aplicación móvil para gestionar deudas personales, recordatorios, pagos parciales, intereses y resúmenes mensuales.', tech: ['Dart', 'Flutter', 'SQLite'], image: '/assets/images/LOGO_SIN_FONDO.png', demo: 'https://github.com/hxtxrchq/payreminder/releases/tag/App', github: 'https://github.com/hxtxrchq/payreminder/tree/App', type: 'mobile' },
  { title: 'Panel de riego automático', description: 'Panel web conectado a ESP32 para monitorear la humedad del suelo y automatizar el riego de una maceta.', tech: ['HTML', 'ESP32', 'IoT'], image: '/assets/images/repo-iot.png', demo: 'https://hxtxrchq.github.io/repo-flowerpot-iot/', github: 'https://github.com/hxtxrchq/repo-flowerpot-iot', type: 'iot' },
  { title: 'Wiki de personajes - Final Space', description: 'Aplicación tipo wiki que consume una API externa para listar personajes, imágenes y detalles de la serie.', tech: ['TypeScript', 'JavaScript', 'API REST'], image: '/assets/images/logo.jpg', demo: 'https://finalspace-characters.chiqo.site/', github: 'https://github.com/hxtxrchq/-FinalSpace-characters', type: 'web' },
];
const skillGroups = [
  ['Lenguajes', 'Python', 'Java', 'C#', 'JavaScript', 'TypeScript'], ['Frontend', 'React', 'Next.js', 'Angular', 'HTML', 'CSS', 'TailwindCSS', 'WordPress'], ['Backend', 'Node.js', 'Express.js', 'APIs RESTful', 'Microservicios Java', 'Cliente-Servidor'], ['Datos', 'MySQL', 'PostgreSQL', 'MongoDB'], ['Cloud y DevOps', 'DigitalOcean', 'Docker', 'Git', 'GitHub', 'CI/CD'], ['IA', 'Claude', 'GitHub Copilot', 'Google Gemini'], ['Gestión', 'Scrum', 'ITIL 4', 'PMBOK 6', 'RUP', 'CRISP-DM'], ['Diseño y herramientas', 'Figma', 'Photoshop', 'Power BI', 'JIRA', 'Notion', 'Microsoft Office'],
];
const certifications = [['DataCamp', 'Intermediate Java', 'Estructuras y buenas prácticas de programación orientada a objetos en Java.'], ['DataCamp', 'Optimizing Code in Java', 'Técnicas de optimización y rendimiento para código Java.'], ['DataCamp', 'Intermediate SQL', 'Consultas avanzadas, joins y manejo de bases de datos relacionales.'], ['freeCodeCamp', 'Scientific Computing with Python', 'Cómputo científico y análisis numérico con Python.'], ['DataCamp', 'Software Development with GitHub Copilot', 'IA como asistente de desarrollo para acelerar y mejorar la calidad del código.'], ['Tecsup', 'Programa Integral de INNOVALAB', 'Innovación y desarrollo de soluciones tecnológicas aplicadas.'], ['UPAO 2025', 'Ponente - Semana Tecnológica', 'Optimización de un modelo híbrido Autoencoder con Random Forest para detectar anomalías.']];

function SectionHeading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) { return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{intro && <p>{intro}</p>}</div>; }

function AvatarDisplay() {
  return <div className="hero-visual"><div className="hero-ring" /><div className="avatar-glow" /><img src="/assets/images/3D_Chiqo.png" alt="Avatar 3D de Alonso Paredes" draggable="false" /><div className="hero-label label-bottom">PER / 2026</div></div>;
}

export function VisualMode() {
  const [menuOpen, setMenuOpen] = useState(false); const [filter, setFilter] = useState('all'); const [projectView, setProjectView] = useState<'cards' | 'orbit'>('cards'); const [showAll, setShowAll] = useState(false); const [formStatus, setFormStatus] = useState(''); const lastSubmit = useRef(0);
  useEffect(() => { const elements = document.querySelectorAll<HTMLElement>('.section-block, .reveal-on-scroll'); if (!('IntersectionObserver' in window)) { elements.forEach((element) => element.classList.add('is-visible')); return; } const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: .14 }); elements.forEach((element) => observer.observe(element)); return () => observer.disconnect(); }, []);
  const filteredProjects = filter === 'all' ? projects : projects.filter((project) => project.type === filter); const visibleProjects = showAll ? filteredProjects : filteredProjects.slice(0, 6); const nav = ['about', 'projects', 'experience', 'certifications', 'contact'];
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { const form = event.currentTarget; const data = new FormData(form); const name = String(data.get('name') || '').trim(); const email = String(data.get('email') || '').trim(); const message = String(data.get('message') || '').trim(); const honeypot = String(data.get('_gotcha') || ''); const dangerous = /(<\/?script|javascript:|\b(SELECT|INSERT|UPDATE|DELETE|DROP|UNION|ALTER|EXEC)\b|--|;)/i; if (honeypot || dangerous.test(`${name} ${email} ${message}`)) { event.preventDefault(); setFormStatus('No se pudo validar el mensaje.'); return; } if (name.length < 2 || name.length > 80 || message.length < 10 || message.length > 2000 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) { event.preventDefault(); setFormStatus('Revisa los campos: email válido y mensaje de 10 a 2000 caracteres.'); return; } if (Date.now() - lastSubmit.current < 30000) { event.preventDefault(); setFormStatus('Espera unos segundos antes de enviar otro mensaje.'); return; } lastSubmit.current = Date.now(); setFormStatus('Enviando mensaje...'); };
  return <div className="portfolio-shell">
    <header className="site-header"><a href="#home" className="brand"><span className="brand-mark"><img src="/assets/images/rayito-transparent.png" alt="" /></span><span>ALONSO<br /><small>PAREDES</small></span></a><nav className="desktop-nav">{nav.map((item) => <a key={item} href={`#${item}`}>{item === 'about' ? 'Sobre mí' : item === 'projects' ? 'Proyectos' : item === 'experience' ? 'Trayectoria' : item === 'certifications' ? 'Certificaciones' : 'Contacto'}</a>)}</nav><a className="header-cta" href="#contact">Hablemos <ArrowUpRight size={15} /></a><button className="menu-button" aria-label="Abrir menú" onClick={() => setMenuOpen(true)}><Menu /></button></header>
    {menuOpen && <div className="mobile-menu"><button className="close-menu" aria-label="Cerrar menú" onClick={() => setMenuOpen(false)}><X /></button>{nav.map((item) => <a key={item} href={`#${item}`} onClick={() => setMenuOpen(false)}>{item === 'about' ? 'Sobre mí' : item === 'projects' ? 'Proyectos' : item === 'experience' ? 'Trayectoria' : item === 'certifications' ? 'Certificaciones' : 'Contacto'}</a>)}</div>}
    <main>
      <section id="home" className="hero-section"><div className="hero-copy reveal-on-scroll"><p className="eyebrow"><span className="online-dot" /> Disponible para nuevos proyectos</p><h1>Hola, soy<br /><span>Alonso.</span></h1><p className="hero-role">Full Stack Developer <i>/</i> Java · React · C# .NET · IA</p><p className="hero-intro">Ingeniero de Computación y Sistemas. Diseño y construyo productos digitales completos: interfaces precisas, APIs robustas, datos bien organizados y soluciones potenciadas con IA.</p><div className="hero-actions"><a className="button button-primary" href="/assets/images/CV_ALONSO_PAREDES.pdf" target="_blank" rel="noreferrer"><Download size={16} /> Descargar CV</a><a className="button button-quiet" href="#projects">Explorar proyectos <ArrowUpRight size={16} /></a></div><div className="social-row"><a href="https://www.linkedin.com/in/carlos-alonso-paredes-quiroz-84b94038b/" target="_blank" rel="noreferrer"><Linkedin size={17} /> LinkedIn</a><a href="https://github.com/hxtxrchq" target="_blank" rel="noreferrer"><Github size={17} /> GitHub</a><a href="https://wa.me/51914754513" target="_blank" rel="noreferrer"><MessageCircle size={17} /> WhatsApp</a></div></div><div className="reveal-on-scroll"><AvatarDisplay /></div></section>
      <section id="about" className="about-section section-block reveal-on-scroll"><SectionHeading eyebrow="01 / Sobre mí" title="Pienso en producto. Construyo sistemas." /><div className="about-grid"><div className="about-image"><img src="/assets/images/foto.jpg" alt="Alonso Paredes" /><div className="image-caption">Trujillo, Perú <span>●</span></div></div><div className="about-content"><p className="lead">Convierto problemas complejos en experiencias digitales claras, conectando diseño, lógica y tecnología para que una idea pueda convertirse en un producto real.</p><p>Soy Ingeniero de Computación y Sistemas con dominio full stack: desarrollo interfaces, APIs, bases de datos y despliegues con React, TypeScript, Node.js, Java y C# .NET. También uso herramientas de IA para prototipar, automatizar y elevar la calidad del código.</p><div className="about-trajectory"><strong>+2</strong><span>AÑOS DE EXPERIENCIA<br />PROFESIONAL</span></div></div></div></section>
      <section id="skills" className="skills-section section-block"><SectionHeading eyebrow="02 / Stack" title="Las herramientas que uso para pensar." /><div className="skills-grid">{skillGroups.map(([group, ...skills]) => <div className="skill-group" key={group}><h3><Code2 size={15} />{group}</h3><div>{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div>)}</div></section>
      <section id="projects" className="projects-section section-block"><div className="section-heading-row"><SectionHeading eyebrow="03 / Proyectos" title="Trabajo seleccionado." intro="Ideas que llegaron a producción." /><div className="project-controls"><div className="filter-row">{[['all', 'Todos'], ['web', 'Web'], ['ia', 'IA'], ['desktop', 'Desktop'], ['mobile', 'Mobile'], ['iot', 'IoT']].map(([value, label]) => <button className={filter === value ? 'active' : ''} key={value} onClick={() => { setFilter(value); setShowAll(false); }}>{label}</button>)}</div><div className="view-switch"><button className={projectView === 'cards' ? 'active' : ''} onClick={() => setProjectView('cards')}>▦ Tarjetas</button><button className={projectView === 'orbit' ? 'active' : ''} onClick={() => setProjectView('orbit')}>✦ Orbital</button></div></div></div><div className={`projects-grid ${projectView === 'orbit' ? 'projects-orbit' : ''}`}>{visibleProjects.map((project, index) => <article className="project-card" key={project.title}><div className="project-image"><img src={project.image} alt={project.title} /><span className="project-number">{String(index + 1).padStart(2, '0')}</span></div><div className="project-info"><div><span className="project-type">{project.type}</span><h3>{project.title}</h3><p>{project.description}</p><div className="tag-row">{project.tech.map((tech) => <span key={tech}>{tech}</span>)}</div></div><div className="project-links">{project.demo && <a href={project.demo} target="_blank" rel="noreferrer">Ver demo <ExternalLink size={14} /></a>}{project.github && <a href={project.github} target="_blank" rel="noreferrer">GitHub <Github size={14} /></a>}</div></div></article>)}</div>{filteredProjects.length > 6 && <button className="more-projects" onClick={() => setShowAll(!showAll)}>{showAll ? 'Ver menos' : `Ver más proyectos (${filteredProjects.length - 6})`} <ArrowUpRight size={15} /></button>}</section>
      <section id="experience" className="experience-section section-block"><SectionHeading eyebrow="04 / Trayectoria" title="Dónde he dejado huella." /><div className="timeline"><div className="timeline-item"><span className="timeline-date">FEB 2026 - JUL 2026</span><div><h3>Desarrollador Web <em>PixelBros</em></h3><p>Desarrollo y mantenimiento de sitios y aplicaciones web responsivas con React, TypeScript y Express.js; lógica de negocio, integración de APIs y despliegue en DigitalOcean.</p></div></div><div className="timeline-item"><span className="timeline-date">MAY 2025 - SEP 2025</span><div><h3>Desarrollador de Diseño Web <em>Agencia DN</em></h3><p>Desarrollo y diseño de páginas web con HTML, CSS, JavaScript, React y WordPress; integración de pasarelas de pago, analítica y optimización SEO.</p></div></div><div className="timeline-item education"><span className="timeline-date">AGO 2021 - JUL 2026</span><div><h3>Ingeniero de Computación y Sistemas <em>UPAO</em></h3><p>Formación en algoritmos, bases de datos, arquitectura, desarrollo de software y gestión de proyectos. Décimo superior.</p></div></div></div></section>
      <section id="certifications" className="certifications-section section-block"><SectionHeading eyebrow="05 / Certificaciones" title="Certificaciones que se convierten en práctica." /><div className="cert-grid">{certifications.map(([provider, title, description]) => <article className="cert-card" key={title}><div className="cert-icon"><Award size={17} /></div><div><span>{provider}</span><h3>{title}</h3><p>{description}</p></div><Check className="cert-check" size={15} /></article>)}</div></section>
      <section id="contact" className="contact-section section-block"><div className="contact-heading"><span className="eyebrow">06 / Contacto</span><h2>Hagamos algo<br /><span>que importe.</span></h2><p>¿Tienes una idea, un proyecto o una oportunidad? Mi bandeja está abierta.</p><div className="contact-links"><a href="mailto:calonsoparedes1@gmail.com"><Mail size={17} /> calonsoparedes1@gmail.com</a><a href="https://wa.me/51914754513" target="_blank" rel="noreferrer"><MessageCircle size={17} /> +51 914 754 513</a></div></div><form action="https://formspree.io/f/mrbkowev" method="POST" className="contact-form" onSubmit={handleSubmit}><div className="contact-ray" aria-hidden="true"><img src="/assets/images/rayito-transparent.png" alt="" /></div><div className="form-intro"><Sparkles size={17} /><span>Cuéntame qué quieres construir</span></div><div className="form-row"><label>Tu nombre<input type="text" name="name" maxLength={80} required placeholder="¿Cómo te llamas?" /></label><label>Tu email<input type="email" name="email" maxLength={120} required placeholder="tu@email.com" /></label></div><label>Tu mensaje<textarea name="message" required maxLength={2000} rows={7} placeholder="Cuéntame un poco sobre tu proyecto..." /></label><input type="text" name="_gotcha" tabIndex={-1} autoComplete="off" aria-hidden="true" className="honeypot" /><input type="hidden" name="_captcha" value="false" /><input type="hidden" name="_next" value="https://hxtxrchq.github.io/Portfolio/gracias.html" /><button className="button button-primary form-submit" type="submit">Enviar mensaje <Send size={15} /></button>{formStatus && <p className="form-status" aria-live="polite">{formStatus}</p>}</form></section>
    </main><footer><span>© 2026 Alonso Paredes</span><span>Diseñado y construido con intención.</span><div><a href="https://github.com/hxtxrchq" target="_blank" rel="noreferrer"><Github /></a><a href="https://www.linkedin.com/in/carlos-alonso-paredes-quiroz-84b94038b/" target="_blank" rel="noreferrer"><Linkedin size={18} /></a></div></footer>
  </div>;
}